trigger:
- master

resources:
- repo: self

variables:
  tag: 46
  #'$(Build.BuildId)'

stages:

# Stage 1
# Build Docker Image
# Publish the K8S Files
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     containerRegistry: 'ravinder-dockerhub'
    #     repository: 'ravindercheemadevops/exchange-webservice'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    #     tags: '$(tag)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          target/*
        TargetFolder: '$(Build.ArtifactStagingDirectory)/prod'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/prod'
        ArtifactName: 'prodmanifests'
        publishLocation: 'Container'
    
    - task: S3Download@1
      inputs:
        awsCredentials: 'aws-s3-connection'
        regionName: 'us-east-2'
        bucketName: 'deviousbootcamp-canada'
        sourceFolder: 'qa-artifacts'
        globExpressions: '*.yaml'
        targetFolder: '$(Build.ArtifactStagingDirectory)/qa'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/qa'
        ArtifactName: 'qamanifests'
        publishLocation: 'Container'