trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:

# Stage 1
# Build Docker Image
# Publish the K8S Files
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SonarQubePrepare@4
      inputs:
        SonarQube: 'Jiang-sonarqube-connection'
        scannerMode: 'Other'
        extraProperties: |
          # Additional properties that will be passed to the scanner, 
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          mvn sonar:sonar \
            -Dsonar.projectKey=exchange-webservice \
            -Dsonar.host.url=http://52.168.147.29:9000 \
            -Dsonar.login=95ee831189f762f235d6689bc4a3ed5f701776f9
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'ravinder-dockerhub'
        repository: 'ravindercheemadevops/exchange-webservice'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

# Stage 2
# Download the K8S Files
# Deploy to K8S Cluster with Docker Image
- stage: Deploy
  displayName: Deploy image
  jobs:  
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'Ravinder-azure-kubernetes-cluster'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'ravindercheemadevops/exchange-webservice:$(tag)'